config/routes.rb
SuncorpNpsApp::Application.routes.draw do

  resources :search_suggestions

  get "feedback/new"
  get "feedback/create"

  match "/settings" => "settings#index"
  match "/settings/swap" => "settings#swapWidget"
  match "/settings/blist" => "settings#gblistIndex", :as => :gblist
  match "/settings/blist/add" => "settings#gblistAdd", :as => :gb_add
  match "/settings/blist/remove" => "settings#gblistRemove", :as => :gb_remove
  match "/settings/blist/addcsv" => "settings#gblistAddCsv", :as => :gb_addcsv

  resources :teams
  match 'teams/:id/updateTeam' => "teams#changeRole"
  match 'teams/:id/addMember' => "teams#addMember", :as => :team_add_member
  match 'teams/:id/deleteMember' => "teams#deleteMember"
  
  devise_scope :user do
    devise_for :users, :controllers => {:registrations => "users/registrations"}
    get "/", :to => "devise/sessions#new"
    get "/profile" => "users/registrations#edit", :as => :profile
  end
  
  resources :services
  
   match 'services/:id' => 'services#show'
   match 'services/:id/report' => 'services#report', :as => :service_report  
   match 'services/:id/reportSubmit' => 'services#reportSubmit'
   match '/services' => "services#index", as: :user_root
   match 'services/:id/report_pdf' => 'services#print', :as => :service_print 

  resources :surveys

   match 'services/:id/survey' => 'surveys#index', :as => :surveyindex
   match 'services/:id/survey/add' => 'surveys#addEmail', :as => :add
   match 'services/:id/survey/remove' => 'surveys#removeEmail', :as => :add
   match 'services/:id/survey/upload' => 'surveys#upload', :as => :surveys_upload
   match 'services/:id/survey/sendEmail' => 'surveys#sendEmail', :as => :send_email
   match 'survey' => 'surveys#survey', :as => :survey
   match 'thankyou' => 'surveys#submitSurvey'
   match 'services/:id/survey/blacklist' => 'surveys#blacklist'
   match 'services/:id/survey/dlistremove' => 'surveys#dlistRemove'
   match 'services/:id/survey/dlistadd' => 'surveys#dlistAdd', :as => :d_add
   match 'services/:id/survey/dlistaddcsv' => 'surveys#dlistAddCsv', :as => :dlistAddCsv
   match 'services/:id/survey/blistremove' => 'surveys#blistRemove'
   match 'services/:id/survey/blistadd' => 'surveys#blistAdd', :as => :b_add
   match 'services/:id/survey/blistaddcsv' => 'surveys#blistAddCsv', :as => :blistAddCsv
   match 'services/:id/emaillists' => 'surveys#emailListIndex', :as => :emaillists
   
  resources :feedback 
   match 'feedback/new' => 'feedback#mail', :as => :mail

  root :to => "devise/sessions#new"
  match '*path' => redirect('/')

end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :email_content, :name, :team_id
  
  validates :name, :presence => true
  validates :team, :presence => true
  
  belongs_to :team
  has_many :dlists
  has_many :blists

  has_many :surveys
  has_many :servicesusers
  has_many :users, :through => :servicesusers

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # Devise before filter
  before_filter :authenticate_user!
  # this helper_method call is required in order to register the helper methods.
  helper_method(:sort_column, :sort_direction)
  
  include ReportsHelper
  include ServicesHelper
  include WidgetsHelper
  include ApplicationHelper

  # Exchange Web Services Interface - lib/ews.rb
  require_dependency 'ews'
  include Ews
  
  # Shows all services which belongs to the team which the users belong in by saving them into @teamServices
  #
  # * *Arguments*    :
  #   - nil
  # * *Returns* :
  #   - nil
  #
  def index
    #@teamServices = Service.where('team_id = ?', current_user.team_id).order(sort_column + " " + sort_direction)
    teams = Team.joins(:users).where("user_id = ?", current_user.id)    
    @teamServices = Service.joins(:team).where(:team_id => teams).order(sort_column + " " + sort_direction)
    @otherServices = Service.joins(:users).where('user_id = ?', current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @services }
    end  
  end

  # Show service details and handle EWS inputs.
  #
  # * *Arguments*    :
  #   - nil
  # * *Returns* :
  #   - nil
  #
  def show 
    #caching Service.find(params[:id])
    s = Service.find(params[:id])
    
    #check if service shared with current user
    temp = Service.joins(:users).where('user_id = ?', current_user.id).limit(1).first
    temp_teams = Team.joins(:users).where("user_id = ?", current_user.id)
    temp_arr = []
    temp_teams.each do |t|
      temp_arr.push(t.id)
    end
    #if it's not shared AND does not belong to his team, redirect
    if !checkService(s)
      redirect_to services_path, alert: "You do not have the privileges required to view this service."
    else
      #otherwise, display service
      @service = s

      # flags to assist with correct email folder display
      @no_folder = nil
      @choose_folder = nil
      @have_folder = nil

      # If no folder record exists, set no_folder flag to true, otherwise set have_folder to the folder name
      ews_folder = Servicesuser.where("service_id = ? AND user_id = ?" , params[:id], current_user.id).limit(1).first
      if ews_folder.nil?
        @no_folder = true
      else
        @have_folder = ews_folder.ews_name
      end

      # If a user has attemnpted to login to change a exchange folder enter this branch
      if params[:user_name].present? || params[:password].present?
        begin
          @ews_folders = getFolders(params[:user_name], params[:password]) #method from Ews module, loads Hash{id=>folderName}
          flash[:ews_folders] = @ews_folders
          if ews_folder.nil?
            @ewsID = 0 #ewsID is the default select_box item to show. has a blank default at index 0
          else
            @ewsID = ews_folder.ews_id
          end
          @choose_folder = true
          flash.now[:notice] = "Your Exchange Login was successful. Please select a folder from the list below."
        rescue
          @choose_folder = false # Just incase it was set to true above...
          flash.now[:alert] = "The Exchange username/password entered is incorrect. Please try again."
        end
      end

      # Triggers this branch if a change of folder request has come through
      # :ews_select is the ID of the select box
      if params[:ews_select].present?
        if ews_folder.nil?
          new_ews = Servicesuser.new(:service_id => params[:id], :user_id => current_user.id, :ews_id => params[:ews_select], :ews_name => flash[:ews_folders][params[:ews_select]])
          new_ews.save
          @have_folder = new_ews.ews_name
          flash.now[:notice] = "Your monitored Exchange folder has been successfully changed."

        elsif params[:ews_select] != ews_folder.ews_id
          ews_folder.update_attribute(:ews_id, params[:ews_select])
          ews_folder.update_attribute(:ews_name, flash[:ews_folders][params[:ews_select]])
          @have_folder = ews_folder.ews_name  
          flash.now[:notice] = "Your monitored Exchange folder has been successfully changed."
        end
      end
      
      #show all users not shared the service
      @team = @service.team
      
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @service }
      end
    end
  end

  # Renders a new service page with default team value set if the user has just created a team
  #
  # * *Arguments*    :
  #   - nil
  # * *Returns* :
  #   - nil
  #
  def new
    @service = Service.new
    @teams = current_user.teams.where('role = ?', 'admin')
    @myTeam = params[:myTeam]
    @buttonvalue = "create service"
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @service }
    end
  end

  # Renders edit service page. Redirect user if he is not a admin of the team.
  #
  # * *Arguments*    :
  #   - nil
  # * *Returns* :
  #   - nil
  #
  def edit
    @service = Service.find(params[:id])
    if !checkServiceAdmin(@service)
      redirect_to services_path, alert: "You do not have the privileges required to edit this team."
    else
      @teams = current_user.teams.where('role = ?', 'admin')
      @buttonvalue = "update service"
      @myTeam = params[:myTeam]
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @service }
      end
    end
  end

  # Creates a service and set its team.
  #
  # * *Arguments*    :
  #   - nil
  # * *Returns* :
  #   - nil
  #
  def create
    @service = Service.new(params[:service])
    # passing teams to create in case service name left blank, required for 'new' action to reload from here
    @teams = current_user.teams.where('role = ?', 'admin')
    @buttonvalue = "create service"

    respond_to do |format|
      if @service.save
        format.html { redirect_to :services, notice: 'Your service has been successfully created.' }
        format.json { render json: @service, status: :created, location: @service }
      else
        format.html { render action: "new" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end


  # Update service information if user is an admin
  #
  # * *Arguments*    :
  #   - nil
  # * *Returns* :
  #   - nil
  #
  def update
    @service = Service.find(params[:id])
    @buttonvalue = "update service"
    
    respond_to do |format|
      if checkServiceAdmin(@service) && @service.update_attributes(params[:service])
        format.html { redirect_to @service, notice: 'Your service has been successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # Deletes a service if user is an admin
  #
  # * *Arguments*    :
  #   - nil
  # * *Returns* :
  #   - nil
  #
  def destroy
    @service = Service.find(params[:id])
    
    if checkServiceAdmin(@service)
      @service.destroy
      respond_to do |format|
        format.html { redirect_to services_url }
        format.json { head :no_content }
      end
    else
      redirect_to services_path, alert: "You do not have the privileges required to delete this team."
    end
  end
  
  # Generates a report from 5 months ago till now in months.
  #
  # * *Arguments*    :
  #   - nil
  # * *Returns* :
  #   - nil
  #
  def report
    @service = Service.find(params[:id])
    
    if !checkService(@service)
      redirect_to services_path, alert: "You do not have the privileges required to view this service."
    else
      @date = Hash.new
      @date["start"] = DateTime.now - 5.months
      @date["end"] = DateTime.now
      @date["step"] = "Months"
      
      respond_to do |format|
        format.html # report.html.erb
        format.json { render json: @service }
      end
    end
  end
  
  # Generate a new report depending on the start date, end date, and step.
  #
  # * *Arguments*    :
  #   - nil
  # * *Returns* :
  #   - nil
  #
  def reportSubmit  
    @date = Hash.new
    @service = Service.find(params[:id])
    if !checkService(@service)
      redirect_to services_path, alert: "You do not have the privileges required to view this service."
    else
      @date["start"] = Date.new(params[:syr].to_i, params[:smth].to_i, params[:sday].to_i)
      @date["end"] = Date.new(params[:eyr].to_i, params[:emth].to_i, params[:eday].to_i)
      @date["step"] = params[:step]
      @service = Service.find(params[:id])
      respond_to do |format|
        format.html {render :layout=>false}
        format.json { render json: @service }
      end
    end
  end

  # Generate a pdf with PDFKit using template 'pdf.html.erb' and css file 'pdf.css'
  #
  # * *Arguments*    :
  #   - nil
  # * *Returns* :
  #   - nil
  #
 def print
   @service = Service.find(params[:id])
   @date = params[:post]

   html=render_to_string("services/pdf.html.erb",:post=>@date,:layout=>false)
   kit = PDFKit.new(html, :page_size => 'Letter')
   kit.stylesheets << "#{Rails.root.to_s}/app/assets/stylesheets/pdf.css"
   send_data(kit.to_pdf, :type => :pdf,:disposition  => "inline") 
  end
end

app/helpers/services_helper.rb
module ServicesHelper
  # sort_column & sort_direction are private helper methods for setting current sortable column, and sort directon
  # prevents SQL injection by checking user input and providing safe defaults.

  # Get score of a service
  #
  # Score is calculated by subtracting detractors from promoters and dividing by total responses
  # eg: total 100, P=70, N=10, D=20 -> Score = 50/100, which is 0.5 or 50%
  #
  # * *Arguments*    :
  #   - +service+ -> Service to get score
  # * *Returns* :
  #   - Integer of score
  #
  def get_score(service)
    promoters = 0
    detractors = 0
    count = 0
    service.surveys.each do |survey|
      survey.results.each do |res|
        if res.done == false
          next
        end
        tempScore = res.score
        # Adding to_integer method to try and weed out bad data.
        if tempScore.to_i >= 9 && tempScore.to_i <= 10
          promoters += 1
        elsif tempScore.to_i >= 0 && tempScore.to_i <= 6
          detractors += 1
        end
        count +=1
      end      
    end
    
    if count == 0
      return 0
    end
    return ((promoters - detractors).to_f/count * 100).round()
  end
  
  
  # Get trend of a service, comparing score of previous month and this month
  #
  # 0 for uptrend
  # 1 for no trend
  # 2 for downtrend
  #
  # * *Arguments*    :
  #   - +service+ -> Service to get trend
  # * *Returns* :
  #   - Integer of 0, 1, or 2
  #
  def get_trend(service)
    lastMonth = Hash.new
    thisMonth = Hash.new
    
    lastMonth["promoters"] =0
    lastMonth["neutrals"] =0
    lastMonth["detractors"] =0
    thisMonth["promoters"] =0
    thisMonth["neutrals"] =0
    thisMonth["detractors"] =0
    service.surveys.each do |survey|
      survey.results.reorder('updated_at').each do |res|
        
        if res.done == false || res.updated_at <= DateTime.now - 2.months
          next
        end

        if res.updated_at <= DateTime.now - 30.days
           if res.score >8
             lastMonth["promoters"]+=1
            #7, 8 == neutrals
            elsif res.score > 6
              lastMonth["neutrals"]+=1
            #else detractors
            else
              lastMonth["detractors"] +=1
            end
        else
          if res.score >8
             thisMonth["promoters"]+=1
            #7, 8 == neutrals
            elsif res.score > 6
              thisMonth["neutrals"]+=1
            #else detractors
            else
              thisMonth["detractors"] +=1
            end
        end
      end
    end
    
    lastAverage = (lastMonth["promoters"] - lastMonth["detractors"]).to_f / (lastMonth["promoters"] + lastMonth["detractors"] + lastMonth["neutrals"]) * 100
    thisAverage = (thisMonth["promoters"] - thisMonth["detractors"]).to_f / (thisMonth["promoters"] + thisMonth["detractors"] + thisMonth["neutrals"]) * 100
    
    if lastAverage.nan?
      lastAverage = 0
    end
    
    if thisAverage.nan?
      thisAverage = 0
    end
    
    if lastAverage > thisAverage
      return 2
    elsif lastAverage < thisAverage
      return 0
    else 
      return 1
    end
  end
  
  # Use get_trend function and style trend arrows
  #
  # * *Arguments*    :
  #   - +service+ -> Service to get trend
  # * *Returns* :
  #   - String of the style
  #
  def trend_style(service)
    trend = get_trend(service)
    
    return trend*57
 
  end
  
  # Used on the new service page to decide with team, if any to auto populate
  # myTeam is used directly after a team is created from the new service page
  #
  # * *Arguments*    :
  #   - +service+ -> Service to get trend
  #   - +myTeam+ -> Team to be populated, if any
  # * *Returns* :
  #   - Team instance
  #
  def myTeamSelect(service, myTeam)
    if !myTeam.nil?
      return myTeam
    else
     return (service.team.nil?)? "" : service.team.id
    end
  end
  
  # Checks if current user is an admin of the team owning a particular service
  #
  # * *Arguments*    :
  #   - +service+ -> Service to check if user is an admin of
  # * *Returns* :
  #   - Boolean, true if current user is an admin
  #
  def checkServiceAdmin(service) 
    return (current_user.teams.include?(service.team) && is_team_admin(service.team))
  end
  
  # Checks if current user is a member of the team owning a particular service
  #
  # * *Arguments*    :
  #   - +service+ -> Service to check if user is an admin of
  # * *Returns* :
  #   - Boolean, true if current user belongs to the team
  #
  def checkService(service)
    return (current_user.teams.include?(service.team)) 
  end
end

app/views/services/_form.html.erb
<!-- 
	form that is rendered on the new and edit service pages 
-->

<%= form_for(@service) do |f| %>

	<!-- displays relevant alerts if parameters of the form are not being met upon submission -->
	<% if @service.errors.any? %>
		<div class="alert alert-error error_explanation">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<h4><%= pluralize(@service.errors.count, "error") %> prohibited this survey from being saved:</h4>
			<ul>
				<% @service.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div> <!-- END error error -->
	<% end %>

	<!-- field for the user to enter the service name -->
	<%= f.label 'Service Name:' %>
	<%= f.text_field :name, :placeholder => "enter the new service name", :id => "serviceName", :tabindex => "1"%>
	
	<!-- field for the user to enter the content to be included in the survey invitation email -->
	<%= f.label 'Email Content:' %>
	<%=	 f.text_area :email_content, :rows => 10, :placeholder => "enter the content for your email", :tabindex => "2" %>
	
	<!-- dropdown menu for the user to select which team is associated with the service -->
	<%= f.label :team_id, 'Team to Associate Service With:' %>
	<%= f.select(:team_id, (current_user.teams.collect {|p| [ p.name, p.id ]}), :selected => (myTeamSelect(@service, @myTeam)), :tabindex => "3"  )%>
	
	<!-- button to submit the form -->
	
  	<div class="actions">
		<%= f.submit  :class => "red-button pull-right", :id => "serviceButton", :value => @buttonvalue%>
	</div><!-- END actions-->
	<div class="clear"></div>
<% end %>

app/views/services/_servicebottomlinks.html.erb
<!-- 
	links appearing at the base of the service show page
-->

<div class="bottomLinks pull-right">
	<p>
		<% if is_team_admin(@service.team)%>
			<%= link_to 'Delete', @service, method: :delete, data: { confirm: 'Are you sure you want to delete this service?' } %> |
			<%= link_to 'Edit', edit_service_path(@service) %> |
		<% end %>
		<%= link_to 'Home', services_path %> 
	</p>
</div> <!--END bottomLinks-->

app/views/services/edit.html.erb
<!-- 
	edit service page
-->

<div class="row-fluid">
	<div class="span4 offset4 formBox">
		<h2>Editing Service<%=@all%></h2>
		<h3>You can edit the name, email content and associated team of this service.</h3>
		<%= render 'form' %>  <!-- renders the service form -->
	</div><!--END fBox, span4 -->
	<div class="span4"></div>
</div><!-- END row-fluid -->

<div class="bottomLinks pull-right">
	<%= link_to 'Back', @service %> 
</div>  <!-- END bottomLinks -->

app/views/services/index.html.erb
<div class="row-fluid">
	<div class="span9 serviceArea">
		
		<!-- displays a message if the user currently has no services associated with their account -->
		<% if @teamServices.empty? %>
			<!-- displays alerts -->
			<div class="notifications" id="emptyServiceNote">
				<% if flash[:alert].present? %>
					<div class="alert alert-error">
						<button type="button" class="close" data-dismiss="alert">&times;</button>
						<%= alert %>
					</div>  <!-- END alert-error -->
				<% elsif flash[:notice].present? %>
					<div class="alert alert-success">
						<button type="button" class="close" data-dismiss="alert">&times;</button>
						<%= notice %>
					</div>  <!-- END alert-success -->
				<% end %>
			</div>  <!-- END notifications -->
			
			<p class="pull-left" id="emptyServices">You don't seem to have any Services yet. Why not <%= link_to 'create', new_service_path, :class => "link" %> one?</p>
		
		<!-- otherwise displays all associated services -->
		<% else %>
			<%= link_to 'new', new_service_path, :class => 'red-button pull-right create' %>
			<h1>Team Services</h1> 
			
			<!-- displays alerts -->
			<div class="notifications">
				<% if flash[:alert].present? %>
					<div class="alert alert-error">
						<button type="button" class="close" data-dismiss="alert">&times;</button>
						<%= alert %>
					</div>  <!-- END alert-error -->
				<% elsif flash[:notice].present? %>
					<div class="alert alert-success">
						<button type="button" class="close" data-dismiss="alert">&times;</button>
						<%= notice %>
					</div>  <!-- END alert-success -->
				<% end %>
			</div>  <!-- END notifications -->
			
			<!--creates a serviceBox for each associated service -->
			<% count = 0 %>
			<% @teamServices.each do |service| %>
				<% if count == 0 %>
					<div class="row-fluid">
				<% end %>
					<div class="serviceBox span4">
						<%= link_to service.name, service, :class => "serviceLink link" %>
						<span class="serviceScore"><%= link_to get_score(service), service, :class => "noLink"%><%= link_to '%', service, :class => "noLink" %></span>
						<div class="serviceTrend" style="background-position:<%=trend_style(service)%>px 0px"></div>
					</div> <!-- END serviceBox span4 -->
					<% if count == 2 %>
					</div>  <!-- END row-fluid -->
					<% end %>
					
				<% count += 1 %>
				
				<!-- begins a new line of services once 3 services exist on a line -->
				<% if count == 3 %>
					<% count = 0 %>
				<% end %>
			
			<% end %>
			
			<% if count != 0 #Must mean that the above loop has run and we are in the middle of a non closed row-fluid %>
				</div>
			<% end %>
</div><!--END span9 serviceArea -->
	<div class="span3 widgetArea">
			<h1 class="widgetH">Overview</h1>
			
			<%= render 'widgets/widgets' %>

	</div> <!-- END span3 widgetArea -->
		<% end %>
	</div><!--END span9-->

</div><!--END row-fluid-->

<script>
	// Fix for widget area height issues on larget displays. one time run. 
	// Repeat is done in the application layout view, bound to window resize event.
	var amendedHeight = $(window).height() - 128 - 102;
	if ( amendedHeight > $(".widgetArea").height() ) {
		$(".widgetArea").height(amendedHeight);
	}
	
	// temp fix for body height
	if ($('body').height() <= 760 ) {
		$("body").css("height", "auto");
	} else {
		$("body").css("height", "100%");
	}
	
	// temp footer fix on service#index
	$(document).ready(function() {
		if ($(document).height() >= 992) {
			$('footer').css('margin-top', "-128px");
		} else if ($(document).height() >= 864) {
			var margin = $(document).height() - 864;
			$('footer').css('margin-top', "-" + margin + "px");
		}
	});
</script>

app/views/services/new.html.erb
<!--
	new service page
-->

<!-- displays any notifications pertinent to creation of a new service -->
<div class="notifications">
	<% if flash[:alert].present? %>
		<div class="alert alert-error">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= alert %>
		</div> <!-- END alert alert-error -->
		<% elsif flash[:notice].present? %>
		<div class="alert alert-success">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= notice %>
		</div> <!-- END alert alert-success -->
	<% end %>
</div> <!-- END notifications -->

<%= link_to 'create team', new_team_path(:origin => 'services'),:class => 'red-button pull-right create'%> <!-- button to create a new team before a new service is created -->
<div class="row-fluid">
	<div class="span4 offset4 formBox" id="serviceForm">
		<!-- passing :origin as services so that the origin is added to the params hash  -->
		<h2>New Service</h2>
		<h3>You can create a new service. You must be associated with at least one team to create a service.</h3>
		<%= render 'form' %> <!-- renders the service form -->
	</div><!--END fBox, span4 -->
	<div class="span4"></div>
</div><!--END row-fluid -->

<!-- directs the user back to their previous page -->
<div class="bottomLinks pull-right">
	<%= link_to 'Back', @service %> 
</div> <!-- END bottomLinks -->

app/views/services/reportSubmit.html.erb
<!-- renders updated charts -->
<%= render :partial => 'services/reportTemplates/charts' %>


app/views/services/show.html.erb
<!-- 
	displays information about one service
-->

<!-- ews pop up to login to Exchange -->
<div id="ews-login" class="modal hide fade in" style="display: none; ">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">×</a>
		<h3 style="color: transparent;">Exchange Login</h3>
	</div> <!-- END modal-header -->
	<div class="modal-body">
		<% if ENV["EWS_ENDPOINT"].present? %>
			<h2>EWS Login</h2>
			<h3>Login to Exchange to select a folder to monitor</h3>
			<%= form_tag( service_path, :method => "post") do %>
				<%= label_tag(:user_name, "Username:") %>
				<%= text_field_tag(:user_name, nil, :tabindex => "1") %>
				<%= label_tag(:password, "Password:") %>
				<%= password_field_tag(:password, nil, :tabindex => "2") %>
				<%= submit_tag("login", :class => "red-button pull-right") %>
			<% end %>
		<% else %>
			<p style="text-align: center">Sorry, your administrator has not enabled Exchange Access</p>
		<% end %>
	</div> <!-- END modal-body -->
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">Cancel</a>
	</div> <!-- end modal-footer -->
</div> <!-- END modal hide fade in -->
		

<div class="serviceHeadings">
	<h1 class="service"><%= @service.name %></h1>
	<h2 class="teamName" class="pull-left"><%= @service.team.name %> Team</h2>
</div> <!-- END serviceHeadings -->
<div class="clear"></div>

<%= render 'serviceLinks'%> <!-- renders the inner navigation for single service -->

<!-- displays service alerts -->
<div class="notifications">
	<% if flash[:alert].present? %>
		<div class="alert alert-error">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= alert %>
		</div> <!-- END alert-error -->
	<% elsif flash[:notice].present? %>
		<div class="alert alert-success">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= notice %>
		</div> <!-- end alert-success -->
	<% end %>
</div> <!-- END notifications -->

<div class="row-fluid">
	
	<div class="span6 serviceContent">
		<h2>Monitored Inbox Folder</h2>
		<h3>This is the email folder you would like to monitor for customers.</h3>

		<!-- displays the choose monitored folder dropbox if Exchange has been logged in to -->
		<% if @choose_folder.present? %>
			<p>Please select a folder from the list below.</p>
			<%= form_tag service_path, :id => "ews_form" do %>
  				<%= label_tag(:ews_select, "Exchange Folder") %>
  				<%= select_tag(:ews_select,options_for_select(@ews_folders.collect {|f| [ f[1], f[0] ]}, @ewsID), {:include_blank => true})%>
  				<div><%= submit_tag("select folder", :class => "red-button pull-right") %> </div>
			<% end %>
		
		<!-- displays the monitored email folder if a folder has already been selected -->
		<% elsif @have_folder.present? %>
			<p>Currently monitoring the folder: <strong><em><%= @have_folder %>.</em></strong></p>
			<p><a data-toggle="modal" href="#ews-login" class="red-button pull-right">change folder</a></p>

		<!-- displays the Exchange option if Exchange has not been logged in to -->
		<% elsif @no_folder.present?%>
			<p>You do not have a folder selected for monitoring. Click the button below to select one.</p>
			<p><a data-toggle="modal" href="#ews-login" class="red-button pull-right">select folder</a></p>
		<% end %>
		<div class="clear"></div>
	</div> <!-- END span6 serviceContent -->
	
	<!-- displays the email content entered upon creation or editing of the service -->
	<div class="span6 serviceContent">
		<h2>Email content:</h2>
		<h3>This is the message that will be slotted into the email template.</h3>
		<p><%= @service.email_content %></2>	
	</div> <!-- END span6 serviceContent -->
			
</div> <!-- END row-fluid -->

<%= render "servicebottomlinks"%>
