config/routes.rb
SuncorpNpsApp::Application.routes.draw do

  resources :search_suggestions

  get "feedback/new"
  get "feedback/create"

  match "/settings" => "settings#index"
  match "/settings/swap" => "settings#swapWidget"
  match "/settings/blist" => "settings#gblistIndex", :as => :gblist
  match "/settings/blist/add" => "settings#gblistAdd", :as => :gb_add
  match "/settings/blist/remove" => "settings#gblistRemove", :as => :gb_remove
  match "/settings/blist/addcsv" => "settings#gblistAddCsv", :as => :gb_addcsv

  resources :teams
  match 'teams/:id/updateTeam' => "teams#changeRole"
  match 'teams/:id/addMember' => "teams#addMember", :as => :team_add_member
  match 'teams/:id/deleteMember' => "teams#deleteMember"
  
  devise_scope :user do
    devise_for :users, :controllers => {:registrations => "users/registrations"}
    get "/", :to => "devise/sessions#new"
    get "/profile" => "users/registrations#edit", :as => :profile
  end
  
  resources :services
  
   match 'services/:id' => 'services#show'
   match 'services/:id/report' => 'services#report', :as => :service_report  
   match 'services/:id/reportSubmit' => 'services#reportSubmit'
   match '/services' => "services#index", as: :user_root
   match 'services/:id/report_pdf' => 'services#print', :as => :service_print 

  resources :surveys

   match 'services/:id/survey' => 'surveys#index', :as => :surveyindex
   match 'services/:id/survey/add' => 'surveys#addEmail', :as => :add
   match 'services/:id/survey/remove' => 'surveys#removeEmail', :as => :add
   match 'services/:id/survey/upload' => 'surveys#upload', :as => :surveys_upload
   match 'services/:id/survey/sendEmail' => 'surveys#sendEmail', :as => :send_email
   match 'survey' => 'surveys#survey', :as => :survey
   match 'thankyou' => 'surveys#submitSurvey'
   match 'services/:id/survey/blacklist' => 'surveys#blacklist'
   match 'services/:id/survey/dlistremove' => 'surveys#dlistRemove'
   match 'services/:id/survey/dlistadd' => 'surveys#dlistAdd', :as => :d_add
   match 'services/:id/survey/dlistaddcsv' => 'surveys#dlistAddCsv', :as => :dlistAddCsv
   match 'services/:id/survey/blistremove' => 'surveys#blistRemove'
   match 'services/:id/survey/blistadd' => 'surveys#blistAdd', :as => :b_add
   match 'services/:id/survey/blistaddcsv' => 'surveys#blistAddCsv', :as => :blistAddCsv
   match 'services/:id/emaillists' => 'surveys#emailListIndex', :as => :emaillists
   
  resources :feedback 
   match 'feedback/new' => 'feedback#mail', :as => :mail

  root :to => "devise/sessions#new"
  match '*path' => redirect('/')

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :service
  has_many :results
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  before_filter :authenticate_user!, :except => [:survey, :submitSurvey ]
  before_filter :isadmin, :except => [:survey, :submitSurvey ]
  # this helper_method call is required in order to register the helper methods.
  include ApplicationHelper
  include ServicesHelper

  # Exchange Web Services Interface - lib/ews.rb
  require_dependency 'ews'
  include Ews
  
  # this stores all the entries currently added to the email list.
  @@emailList = Array.new
  
  # Index page for the survey index view.
  #
  # * *Returns* :
  #   - nil
  #
  def index
    @service = Service.find(params[:id])

    if !checkService(@service)
      redirect_to services_path, alert: "You do not have the privileges required to view this service."
    else
      # wipe the email list and start from scratch if a refresh is required
      if params[:refresh]=="true"
        @@emailList = Array.new
        dlist = Dlist.where(:service_id => @service.id)
        for entry in dlist do
          validateAddEmail(entry.email, @service)
        end
      end
  
      # Sets a ews_folder_flag to true if there is a folder record in the database.
      # This is used in the view to determine how to display the EWS option 
      @ews_folder_flag = true if Servicesuser.where("service_id = ? AND user_id = ?" , params[:id], current_user.id).limit(1).first
  
      
      # If a user has attemnpted to login to change a exchange folder enter this branch
        if params[:user_name].present? || params[:password].present?
          begin
            ews_emails = getEmailsEWS(params[:user_name], params[:password])
            addEmailsEWS(ews_emails)
            flash.now[:notice] = "Your email addresses have been successfully loaded."
          rescue
            flash.now[:alert] = "The Exchange username/password entered is incorrect. Please try again."
          end
        end
      
      # Parse csv file if one is uploaded
      if params[:csv].present?
        if (params[:csvfile].nil?)
          flash.now[:alert] = "There was an error while trying to process your CSV file."
        else
          emails = parseCsv(params[:csvfile])
          for email in emails do
            validateAddEmail(email, @service)
          end
        end
      end
      
      @emails = @@emailList
    end
  end

  # Creates empty results entries of all e-mails in the database and send out the e-mails using DelayedJobs
  #
  # * *Arguments*    :
  #   - nil
  # * *Returns* :
  #   - nil
  #
  def sendEmail
    #create database entries
    @service = Service.find(params[:id])
    survey = @service.surveys.create()

    @@emailList.each do |email|
      survey.results.create(:done => false, :email => email, :score => nil, :comments => nil)
      url = "#{request.protocol}#{request.host_with_port}" + ENV["SUB_DIRECTORY"] + "/survey?a=" + encrypt(email) + "&b=" + encrypt(survey.id.to_s)
      Mailer.delay.invitation(email, @service, url)
      #Mailer.invitation(email, @service, url).deliver
    end
    
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Your survey has been sent.' }
      format.json { head :no_content }
    end
  end
  
  # Renders a survey according to encrypted "GET" parameters. 
  #
  # * *Arguments*    :
  #   - nil
  # * *Returns* :
  #   - nil
  # * *Raises* :
  #   - ActiveRecord::RecordNotFound if GET parameters are corrupted
  #
  def survey
    email = decrypt(params[:a])
    surveyId = decrypt(params[:b])
    if email == -1 || surveyId == -1
      raise ActiveRecord::RecordNotFound
    else
      #find or create survey
      
      survey= Survey.find(surveyId)
      @service = survey.service
      #find result with the email
      @result = Result.where(:survey_id => survey.id, :email => email)
     
     if @result.first.nil?
        raise ActiveRecord::RecordNotFound
     else
        respond_to do |format|
          format.html {render :layout=>false}
          format.json { render json: @service }
        end
      end
    end
  end

  # Saves the results of the submitted survey
  #
  # * *Arguments*    :
  #   - nil
  # * *Returns* :
  #   - nil
  # * *Raises* :
  #   - ActiveRecord::RecordNotFound if survey already done
  #    
  def submitSurvey
    email = decrypt(params[:a])
    surveyId = decrypt(params[:b])
    survey = Survey.find(surveyId)
    result = Result.where(:survey_id => survey.id, :email => email).first
    @service = survey.service
    
    if (!result.done?)
      result.done = true
      result.score = params[:score]
      result.comments = params[:comments][:box]
      result.save!
    else
      raise ActiveRecord::RecordNotFound
    end
    respond_to do |format|
      format.html { render :layout=>false }
      format.json { head :no_content }
    end
  end

  
  # Parse an uploaded csv file, and return a list of emails.
  #
  # * *Args*    :
  #   - params -> A StringIO or an instance of File backed by a temporary file
  # * *Returns* :
  #   - Array<string>
  #
  def parseCsv(csvfile)
    emailString = csvfile.read
    return emailString.split(',').map(&:strip)
    #parseCsv no longer adds emails, that is done in validateAddEmail
  end
  
  
  # Add an entry to the email list, if it is a valid email address.
  #
  # * *Arguments*    :
  #   - nil
  # * *Returns* :
  #   - nil
  #
  def addEmail
    service = Service.find(params[:id])
    result = validateAddEmail(params[:email], service)
    @emails = @@emailList
    
    if result == "blacklisted" || result =="existing" || result == "globalblisted"
      render :text => result
    else 
      
      respond_to do |format|
        format.html { render :layout=>false }
        format.json { head :no_content }
      end
    end
    
    
  end


  # Method for obtaining emails to outgoing survey list via Exchange Web Services.
  #
  # 
  # Asks for credentials each request, and will scan a predefined
  # folder nominated by the user for email addresses.
  #
  # * *Args*    :
  #   - +user+ -> The Exchange account username
  #   - +pass+ -> The Exchange account password
  # * *Returns* :
  #   - nil
  # * *Raises* :
  #   - +ArgumentError+ -> If username or password is missing
  #
  def getEmailsEWS(user, pass)
    raise ArgumentError, "Username and Password required" unless (user.present? && pass.present?)
    folder_id = Servicesuser.where("service_id = ? AND user_id = ?" , params[:id], current_user.id).limit(1).first.ews_id
    @folder = getEmailAddresses(user, pass, folder_id)
  end


  # Method for adding emails to outgoing survey list
  #
  # Differs from above implementation, as the above implementation relies
  # on the :email symbol to be present.
  # 
  #
  # * *Arguments*    :
  #   - +emails+ -> The array of email addresses
  # * *Returns* :
  #   - nil
  # * *Raises* :
  #   - +ArgumentError+ -> If array of emails is missing
  #
  def addEmailsEWS(emails)
    raise ArgumentError, "Username and Password required" unless (emails.present?)
    
    service = Service.find(params[:id])
    emails.each do |email|
      validateAddEmail(email, service)
    end
    
    @emails = @@emailList
    
  end
  
  
  # Remove an entry from the email list
  #
  # * *Arguments*    :
  #   - nil
  # * *Returns* :
  #   - nil
  #
  def removeEmail
    email = (params[:email])
    
    if @@emailList.include?(email)
      @@emailList.delete(email)
    end
    
    @emails = @@emailList
    
    respond_to do |format|
      format.html { render :layout=>false }
      format.json { head :no_content }
    end
  end
  
  
  # Add an email to the blist table and remove it from the email list,
  # Then redirect view back to the emailListIndex view.
  #
  # * *Arguments*    :
  #   - nil
  # * *Returns* :
  #   - nil
  #
  def blacklist
    service = Service.find(params[:id])
    if !@isadmin
      redirect_to services_path, alert: "You do not have the privileges required to view this service."
    else
      email = params[:email]
      entry = service.blists.find_or_create_by_email(:email => email)
      @@emailList.delete(email)
      
      respond_to do |format|
        format.html { redirect_to :surveyindex }
        format.json { head :no_content }
      end
    end
  end
  
  
  # Index page for the emailListIndex view.
  #
  # * *Arguments*    :
  #   - nil
  # * *Returns* :
  #   - nil
  #
  def emailListIndex
    @service = Service.find(params[:id])
    if !@isadmin
      redirect_to services_path, alert: "You do not have the privileges required to view this service."
    else
      @dlist = Dlist.where(:service_id => params[:id])
      @blist = Blist.where(:service_id => params[:id])
  
      respond_to do |format|
        format.html
        format.json { head :no_content }
      end
    end
  end
  
  
  # Remove a single email from the dlist table, redirect view back to the emailListIndex view.
  #
  # * *Arguments*    :
  #   - nil
  # * *Returns* :
  #   - nil
  #
  def dlistRemove
    service = Service.find(params[:id])
    if !@isadmin
      redirect_to services_path, alert: "You do not have the privileges required to view this service."
    else
      email = (params[:email])
      entry = Dlist.find_by_email_and_service_id(email, service.id)
      if !entry.nil? 
        entry.destroy
      end
      
      respond_to do |format|
        format.html { redirect_to :emaillists }
        format.json { head :no_content }
      end
    end
  end
  
  # Add a single email to the dlist table, redirect view back to the emailListIndex view.
  #
  # * *Arguments*    :
  #   - nil
  # * *Returns* :
  #   - nil
  #
  def dlistAdd
    service = Service.find(params[:id])
    email = params[:email]
    
    if !@isadmin
      redirect_to services_path, alert: "You do not have the privileges required to view this service."
    else
      
      if emailRegex(email)
        entry = service.dlists.find_by_email(email)
        if !entry.nil?

app/views/surveys/_emaillist.html.erb
<%= stylesheet_link_tag    "application", :media => "all" %>

<!--
	creates a table of emails on the survey index page if the user has provided any emails
-->


<% if @emails.present? %>
	<!-- table of emails to send survey to -->
	<table id = 'email_list'>
		<!--empty <tr> is fix for incorrect row colours -->
		
		<tr>
			<th colspan=<% if @isadmin %> 3 <% else%> 2 <% end %> class="truncate">Emails</th>
			<% if @isadmin %><th class="truncate">Add to Black List <% end %></th>
			<th class="truncate pull-right">Remove</th>
		</tr>	  
		<% i = 0 %>
		<% @emails.each do |email| %> <!-- creates a new row for each email -->
			<tr>
				<td colspan=<% if @isadmin %> 3 <% else%> 2 <% end %> class="truncate"><%= email%></td>
				<% if @isadmin %><td class="link truncate">
					<%= link_to "Add", :controller => "surveys", :action => "blacklist", :email => email %>
			   </td><% end %>
			    <td>
					<%= hidden_field_tag 'remove', email, :id => "remove"+i.to_s%>
					<%= link_to raw("<i class='icon-remove'></i>"), 'javascript:;', :class => 'icon btnRemoveClass pull-right', :id=> "btnRemove" + i.to_s %>
					<% i = i + 1 %>
				</td>

			</tr>
		<% end %>
	</table> <!-- end email table -->
	
	<%= form_tag :send_email  do %>
	<%= submit_tag "send", :name => 'send', :class => 'red-button pull-right'%> <!-- button to send surveys to listed emails -->
	<div class="clear"></div>
<% end %>

<!-- If no emails have been provided, a prompt is provided -->
<% else %>
	<p>Please enter any email addresses you wish to send this survey to.</p>
<% end %>



<script>	
	$(".btnRemoveClass").click(function() {
		var buttonId = this.id.substr(9);
		
		$.ajax ({
			type: "GET",
			url: "<%= "/services/" + params[:id] + "/survey/remove" %>",
			data: {
				email: $("#remove" + buttonId).val()
			},
			dataType: "html",
			success: function(data, status, xhr) {
				$("#emailTable").html(data);
				$("tr:odd").css("background-color", "rgb(245, 248, 248");
			}
		});
	})
	
	
</script>

app/views/surveys/addEmail.html.erb
<!-- 
	refreshes the email list when a new email is added
-->

<%= render 'emaillist'%>

app/views/surveys/emailListIndex.html.erb
<!-- 
	settings for the service, containing options for a black list and distribution list
-->

<div class="serviceHeadings">
		<h1 class="service">Service Settings</h1>
		<h2 class="serviceName" class="pull-left"><%=@service.name%></h2>
	</div> <!-- END serviceHeadings -->
	<div class="clear"></div>
	
	<%= render 'services/serviceLinks'%> <!-- renders the inner navigation for single service -->
	
	<!-- displays notifications pertaining to service settings -->
	<div class="notifications">
		<% if flash[:alert].present? %>
			<div class="alert alert-error">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<%= alert %>
			</div> <!-- END alert-error -->
		<% elsif flash[:notice].present? %>
			<div class="alert alert-success">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<%= notice %>
			</div> <!-- END alert-success -->
		<% end %>
	</div> <!-- END notifications -->

	<div class="contentBox">
		<h2>Email Black List</h2>
		<h3>Emails that can not be included in the send list. Emails can be added manually or by importing a 'comma separated' CSV file.</h3>
		<div class="row-fluid">
			<div class="span8">
				<%= form_tag :b_add, :id => 'b_add' do %>
				  <%= text_field_tag(:email) %>
				  <%= submit_tag("add", :class => "red-button pull-right push-button") %>
				<% end %>
				<div class="clear"></div>
			</div>
     		<div class="span4">
     			<%= form_tag({:action => :blistAddCsv}, :multipart => true, :id=>"content1") do %>
				<%= file_field_tag 'b_csv', :class => "pull-right"%>
				<div class="clear"></div>
			  	<%= submit_tag("upload", :class => "red-button pull-right blist-button-up") %>
				<% end %>
     		</div>
		</div> <!-- END row-fluid -->

		<!-- list of black listed emails for service -->	
		<% if @blist.present? %>
			<table id="blist_table">
			  <tr>
			    <th colspan=2 class = "truncate">Emails</th>
		    <th class = "truncate pull-right"> Remove </th>
			  </tr>
			  <% i = 0 %>
			<% @blist.each do |entry| %>
			  <tr>
			    <td colspan=2 class = "truncate"><%= entry.email%></td>
			    <td class="listIcon pull-right">
				<%= link_to raw("<i class='icon-remove'></i>"), {:controller => "surveys", :action => "blistRemove", :email => entry.email}, {:id =>"rmbtn_" + i.to_s, :class => 'pull-right'}  %>
			    </td>
			  </tr>
			<% i+= 1%>
			<% end %>
			</table>
		
		<% else %>
		<p>Your Black List for this service is currently empty.</p>
		<% end %>
	</div> <!-- END contentBox -->
	
	<!-- emails that are automatically included in the survey email list -->
	<div class="contentBox">
		<h2>Distribution List</h2>
		<h3>Default email list for service. Emails can be added manually or by importing a 'comma separated' CSV file.</h3>
		<div class="row-fluid">
			<div class="span8">
				<%= form_tag :d_add, :id => 'd_add'  do %>
			  		<%= text_field_tag(:email) %>
			  		<%= submit_tag("add", :class => "red-button pull-right") %>
				<% end %>
				<div class="clear"></div>
			</div> <!-- END span8 -->
     		<div class="span4">
     			<%= form_tag({:action => :dlistAddCsv}, :multipart => true,:id=>"content2") do %>
				<%= file_field_tag 'd_csv', :class => "pull-right" %>
				<div class="clear"></div>
		  		<%= submit_tag("upload", :class => "red-button pull-right dlist-button-up") %>
				<% end %>
     		</div> <!-- END span4 -->
		</div> <!-- END row-fluid -->

	<!-- table of default emails -->	
	<% if @dlist.present? %>

		<table id="dlist_table">
		  <tr>
		    <th colspan=2 class = "truncate">Emails</th>
		    <th class = "truncate pull-right"> Remove </th>
		  </tr>
		  <% i = 0 %>
		<% @dlist.each do |entry| %>
		  <tr>
		    <td colspan=2 class = "truncate"><%= entry.email%></td>
		    <td class="listIcon pull-right">
			<%= link_to raw("<i class='icon-remove'></i>"), {:controller => "surveys", :action => "dlistRemove", :email => entry.email}, {:class => "pull-right", :id => "rmbtn_"+i.to_s } %>
		    </td>
		  </tr>
		  <% i = i+0 %>
		<% end %>
		</table>
	
	<% else %>
	<p>This service currently has no emails associated with it.</p>
	<% end %>
	</div> <!-- END contentBox -->
<%= render "services/servicebottomlinks"%>

<style>
	body {
		height: auto;
	}
</style>

app/views/surveys/index.html.erb
<!-- 
	survey page where users can provide email addresses and send the survey
-->


<!-- ews pop up for exchange log in -->
<div id="ews-login" class="modal hide fade in" style="display: none; ">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">×</a>
		<h3 style="color: transparent;">Exchange Login</h3>
	</div> <!-- END modal-header -->
	<div class="modal-body">
		<% if ENV["EWS_ENDPOINT"].present? %>
			<h2>EWS Login</h2>
			<h3>Login to Exchange to select a folder to import email addresses from</h3>
			<%= form_tag( surveyindex_path, :method => "post") do %>
				<%= label_tag(:user_name, "Username:") %>
				<%= text_field_tag(:user_name, nil, :tabindex => "1") %>
				<%= label_tag(:password, "Password:") %>
				<%= password_field_tag(:password, nil, :tabindex => "2") %>
				<%= submit_tag("Login", :class => "red-button pull-right") %>
			<% end %>
		<% else %>
			<p style="text-align: center">Sorry, your administrator has not enabled Exchange Access</p>
		<% end %>
	</div> <!-- END modal-body -->
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">Cancel</a>
	</div> <!-- END modal-footer -->
</div> <!-- END modal hide fade in -->

	
	<div class="serviceHeadings">
		<h1 class="service">Survey</h1>
		<h2 class="serviceName" class="pull-left"><%= @service.name%></h2>
	</div> <!-- END serviceHeadings -->
	<div class="clear"></div>
	
	<%= render 'services/serviceLinks'%> <!-- renders the inner navigation for single service -->
	
	<div class="notifications">
		<% if flash[:alert].present? %>
			<div class="alert alert-error">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<%= alert %>
			</div> <!-- END alert-error -->
		<% elsif flash[:notice].present? %>
			<div class="alert alert-success">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<%= notice %>
			</div> <!-- END alert-success -->
		<% end %>
	</div> <!-- END notifications -->

<!-- if Exchange log in has been provided, displays a 3 section area to choose emails -->	
<% if @ews_folder_flag.present? %>
	<div class="row-fluid">
		<div class ="span4 surveyBox"> <!-- allows users to choose emails through Exchange -->
			<h2>Add Emails Through Exchange</h2>
			<h3>Sync emails from your defined remote tracking Exchange folder</h3>
				<p><a data-toggle="modal" href="#ews-login" class="red-button">Select Folder</a></p>
		</div>	<!-- END span4 surveyBox -->
		
		<div class ="span4 surveyBox"> <!-- allows users to manually enter email addresses -->
			<h2>Add email</h2>
			<h3>Add email addresses manually that are not in system.</h3>
				<%= label_tag(:email) %>
				<div class="clear"></div>
				<%= email_field "email", "email", :placeholder => "enter a valid email address"%>
				<%= button_tag("add email", :class => 'red-button pull-right', :id =>'add') %>
				<div class="clear"></div>
		</div> <!-- END span4 surveyBox -->
		
		<div class ="span4 surveyBox"> <!-- allows users to choose CSV files of email addresses -->
			<h2>Import Email List</h2>
			<h3>Import email lists from 'comma separated' CSV files.</h3>
				<%= form_tag({:action => :index}, :multipart => true) do %>		
					<%= hidden_field_tag 'csv', 'true', :id => 'a'%>	
					<%= file_field_tag 'csvfile', :class => "pull-right" %>
					<div class="clear"></div>
					<%= submit_tag("upload", :class => 'red-button pull-right') %>
				<% end %>
				<div class="clear"></div>
		</div> <!-- END span4 surveyBox -->
	</div> <!-- END row-fluid -->	

<!-- if Exchange log in has not been provide, displays a 2 section area to enter emails -->	
<% else %>
	<div class="row-fluid">
		<div class="span8 surveyBox"> <!-- allows users to maunally enter email addresses -->
			<h2>Add email</h2>
			<h3>Add email addresses manually that are not in system.</h3>
				<%= label_tag(:email) %>
				<div class="clear"></div>
				<%= email_field "email", "email", :placeholder => "enter a valid email address"%>
				<%= button_tag("add email", :class => 'red-button pull-right', :id =>'add') %>
				<div class="clear"></div>
		</div> <!-- END span6 surveyBox -->
		
		<div class="span4 surveyBox"> <!-- allows users to choose CSV files of email addresses -->
			<h2>Import Email List</h2>
			<h3>Import email lists from 'comma separated values' CSV files.</h3>
				<%= form_tag({:action => :index}, :multipart => true) do %>
					<%= hidden_field_tag 'csv', 'true', :id => 'a'%>
					<%= file_field_tag 'csvfile', :class => "pull-right" %>
					<div class="clear"></div>
					<%= submit_tag("upload", :class => 'red-button pull-right button-up') %>
				<% end %>
				<div class="clear"></div>
		</div> <!-- END span6 surveyBox -->
	</div> <!-- END row-fluid -->
<% end %>

<!-- table of all emails provided by the user -->
<div class="row-fluid">	
	<div class="contentBox span12" id="emailTable">
			<%= render 'emaillist' %> <!-- renders the email list -->
	</div>
</div>

<div class="clear"></div>


<%= render "services/servicebottomlinks"%>


<script>
$("#add").click(function() {
	addEmail();
});

  //add member via press enter
$('#email_email').keydown(function (e){
if(e.keyCode == 13) {
	addEmail()
}
});

function addEmail() {
	var emailFilter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
	if (emailFilter.test($("#email_email").val())) {
		$.ajax ({
			type: "POST",

			url: "<%= "#{request.protocol}#{request.host_with_port}" + ENV['SUB_DIRECTORY'] + "/services/" + params[:id] + "/survey/add" %>",
			data: {
				email: $("#email_email").val()
			},
			dataType: "html", 
			success: function(data, status, xhr) {
				if (data == "existing") {
					alert("E-mail address already added");
				} else if (data =="blacklisted") {
					alert("E-mail address is blacklisted by your team admin")
				} else if (data == "globalblisted") {
					alert("Email adress is blackisted by the site admin")
				} else {
					$("#emailTable").html(data);
					$("tr:even").css("background-color", "rgb(245, 248, 248");
  					
				}
			}
		});	
	} else {
		alert("Please enter a valid email address.");
	}
	$("#email_email").val("");
	$("#email_email").focus();
	
}

// temp fix for body height
if ($('body').height() <= 760 ) {
	$("body").css("height", "auto");
} else {
	$("body").css("height", "100%");
}
</script>

app/views/surveys/removeEmail.html.erb
<!-- 
	refreshes the email list when an email is removed
-->

<%= render 'emaillist'%>

app/views/surveys/submitSurvey.html.erb
<!-- 
	page displayed to user when they have completed a survey
-->

<%= stylesheet_link_tag    "application", :media => "all" %> <!-- adds styling to the submitSurvey page, as page is external to the main application -->


<div id="stickyWrap">	<!-- pushes footer to bottom of the browser -->
	<div class="container">
		<div class="row-fluid span12">
			<h1>Survey for <%= @service.name %></h1>
			
			<!-- displays alerts related to survey completion -->
			<div class="notifications">
				<% if flash[:alert].present? %>
					<div class="alert alert-error">
						<button type="button" class="close" data-dismiss="alert">&times;</button>
						<%= alert %>
					</div> <!-- END alert-error -->
				<% elsif flash[:notice].present? %>
					<div class="alert alert-success">
						<button type="button" class="close" data-dismiss="alert">&times;</button>
						<%= notice %>
					</div> <!-- END alert-success -->
				<% end %>
			</div> <!-- END notifications -->
			
			<!-- displays thank you message after the survey has been completed -->
			<div class="row-fluid">
				<div class="span8 offset2 contentBox">
					<p id="thankYou">Thank you</p>
					<p id="surveyMessage">for taking the time to complete this survey.</p>
					<div id="smiley"><img src="assets/smileyface.png" alt="smiling emoticon"></div>
				</div> <!-- END span8 contentBox -->
				<div class="span2"></div> <!-- empty span to keep contentBox positioned correctly -->
			</div> <!-- END row-fluid -->
		</div> <!-- END row-fluid span12 -->
	</div> <!-- END container -->
	
	
	<div id="push"></div> <!-- Used for pushing page content down when necessary for sticky footer -->
</div> <!-- End of stickyWrap -->

<!-- displays footer containing only footer text -->
<footer>	
	<div class="container">
		<div class="row-fluid">
			<div class="span12">
				<div class="footertext">
					<p>:knightcap In-Dev 0.5.5 | Programmers of the Round Table</p>
				</div> <!-- END footertext -->
			</div> <!--END span12-->
		</div> <!--ENd row-fluid-->
	</div> <!--END container-->
</footer> <!-- END footer -->
	